### ISSUE TITLE
Prior container content display not maintained

### ISSUE THREAD

**Issue by smooreace** [Jericho1060/du-container-monitoring#2]
Not sure if this is a bug report or a feature request.

Last night I put 2 kinds of scrap in this container and filled it to the shown % full. This morning I went back to the screen and the content volume is still shown and accurate based on last night's data. But the actual contents are not showing any longer.
![image](https://user-images.githubusercontent.com/35540547/200348613-272a4a44-4be2-4940-a180-9d0fa25616c5.png)

At some point, someone added contents and re-activating the board updates the display based on that new data.
![image](https://user-images.githubusercontent.com/35540547/200350083-795a95fc-aee1-48c7-83c5-fbf6ebf95078.png)

Shouldn't the contents still be showing from my activating the PB last night?
Can the latest contents be stored in a way that would allow them to always be accurate based on the last time the PB was activated, for anyone that looks at the screen?

**Comment by thoda-dev** [comment]
Hi, no the content is not saved on the screen due to the large possible amount of data that could break everything (there is a limit on screens).

If you go to far or if you logout, the screen will become empty and you have to restart the script to see the content.

**Comment by smooreace** [comment]
But it's not really clearing the screen. It's only clearing part of it (the volume remained in the SS above). I'm seeing similar randomness on your other inventory screen LUA as well
